/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RefinanceCheckRouteImport } from './routes/refinance-check'
import { Route as PromotionRouteImport } from './routes/promotion'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CreditCheckRouteImport } from './routes/credit-check'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketIndexRouteImport } from './routes/ticket/index'
import { Route as NotificationIndexRouteImport } from './routes/notification/index'
import { Route as InstallmentIndexRouteImport } from './routes/installment/index'
import { Route as GuideIndexRouteImport } from './routes/guide/index'
import { Route as CouponIndexRouteImport } from './routes/coupon/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TicketHistoryRouteImport } from './routes/ticket/history'
import { Route as ReceiptContractIdRouteImport } from './routes/receipt/$contractId'
import { Route as NotificationIdRouteImport } from './routes/notification/$id'
import { Route as InvoiceContractIdRouteImport } from './routes/invoice/$contractId'
import { Route as GuideIdRouteImport } from './routes/guide/$id'
import { Route as CouponStaffScanRouteImport } from './routes/coupon/staff-scan'
import { Route as CouponScanRouteImport } from './routes/coupon/scan'
import { Route as CouponQrcodeRouteImport } from './routes/coupon/qrcode'
import { Route as CouponIdRouteImport } from './routes/coupon/$id'
import { Route as ContractIdRouteImport } from './routes/contract/$id'
import { Route as ContractContractIdRouteImport } from './routes/contract/$contractId'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as InstallmentPayIndexRouteImport } from './routes/installment/pay/index'
import { Route as ReceiptDetailReceiptIdRouteImport } from './routes/receipt/detail/$receiptId'
import { Route as InvoiceDetailInvoiceIdRouteImport } from './routes/invoice/detail/$invoiceId'
import { Route as InstallmentPayIdRouteImport } from './routes/installment/pay/$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RefinanceCheckRoute = RefinanceCheckRouteImport.update({
  id: '/refinance-check',
  path: '/refinance-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionRoute = PromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCheckRoute = CreditCheckRouteImport.update({
  id: '/credit-check',
  path: '/credit-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIndexRoute = TicketIndexRouteImport.update({
  id: '/ticket/',
  path: '/ticket/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationIndexRoute = NotificationIndexRouteImport.update({
  id: '/notification/',
  path: '/notification/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentIndexRoute = InstallmentIndexRouteImport.update({
  id: '/installment/',
  path: '/installment/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponIndexRoute = CouponIndexRouteImport.update({
  id: '/coupon/',
  path: '/coupon/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketHistoryRoute = TicketHistoryRouteImport.update({
  id: '/ticket/history',
  path: '/ticket/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptContractIdRoute = ReceiptContractIdRouteImport.update({
  id: '/receipt/$contractId',
  path: '/receipt/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationIdRoute = NotificationIdRouteImport.update({
  id: '/notification/$id',
  path: '/notification/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceContractIdRoute = InvoiceContractIdRouteImport.update({
  id: '/invoice/$contractId',
  path: '/invoice/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIdRoute = GuideIdRouteImport.update({
  id: '/guide/$id',
  path: '/guide/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponStaffScanRoute = CouponStaffScanRouteImport.update({
  id: '/coupon/staff-scan',
  path: '/coupon/staff-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponScanRoute = CouponScanRouteImport.update({
  id: '/coupon/scan',
  path: '/coupon/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponQrcodeRoute = CouponQrcodeRouteImport.update({
  id: '/coupon/qrcode',
  path: '/coupon/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponIdRoute = CouponIdRouteImport.update({
  id: '/coupon/$id',
  path: '/coupon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractIdRoute = ContractIdRouteImport.update({
  id: '/contract/$id',
  path: '/contract/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractContractIdRoute = ContractContractIdRouteImport.update({
  id: '/contract/$contractId',
  path: '/contract/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentPayIndexRoute = InstallmentPayIndexRouteImport.update({
  id: '/installment/pay/',
  path: '/installment/pay/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptDetailReceiptIdRoute = ReceiptDetailReceiptIdRouteImport.update({
  id: '/receipt/detail/$receiptId',
  path: '/receipt/detail/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceDetailInvoiceIdRoute = InvoiceDetailInvoiceIdRouteImport.update({
  id: '/invoice/detail/$invoiceId',
  path: '/invoice/detail/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentPayIdRoute = InstallmentPayIdRouteImport.update({
  id: '/installment/pay/$id',
  path: '/installment/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/credit-check': typeof CreditCheckRoute
  '/profile': typeof ProfileRoute
  '/promotion': typeof PromotionRoute
  '/refinance-check': typeof RefinanceCheckRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/blog/$id': typeof BlogIdRoute
  '/contract/$contractId': typeof ContractContractIdRoute
  '/contract/$id': typeof ContractIdRoute
  '/coupon/$id': typeof CouponIdRoute
  '/coupon/qrcode': typeof CouponQrcodeRoute
  '/coupon/scan': typeof CouponScanRoute
  '/coupon/staff-scan': typeof CouponStaffScanRoute
  '/guide/$id': typeof GuideIdRoute
  '/invoice/$contractId': typeof InvoiceContractIdRoute
  '/notification/$id': typeof NotificationIdRoute
  '/receipt/$contractId': typeof ReceiptContractIdRoute
  '/ticket/history': typeof TicketHistoryRoute
  '/blog': typeof BlogIndexRoute
  '/coupon': typeof CouponIndexRoute
  '/guide': typeof GuideIndexRoute
  '/installment': typeof InstallmentIndexRoute
  '/notification': typeof NotificationIndexRoute
  '/ticket': typeof TicketIndexRoute
  '/installment/pay/$id': typeof InstallmentPayIdRoute
  '/invoice/detail/$invoiceId': typeof InvoiceDetailInvoiceIdRoute
  '/receipt/detail/$receiptId': typeof ReceiptDetailReceiptIdRoute
  '/installment/pay': typeof InstallmentPayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/credit-check': typeof CreditCheckRoute
  '/profile': typeof ProfileRoute
  '/promotion': typeof PromotionRoute
  '/refinance-check': typeof RefinanceCheckRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/blog/$id': typeof BlogIdRoute
  '/contract/$contractId': typeof ContractContractIdRoute
  '/contract/$id': typeof ContractIdRoute
  '/coupon/$id': typeof CouponIdRoute
  '/coupon/qrcode': typeof CouponQrcodeRoute
  '/coupon/scan': typeof CouponScanRoute
  '/coupon/staff-scan': typeof CouponStaffScanRoute
  '/guide/$id': typeof GuideIdRoute
  '/invoice/$contractId': typeof InvoiceContractIdRoute
  '/notification/$id': typeof NotificationIdRoute
  '/receipt/$contractId': typeof ReceiptContractIdRoute
  '/ticket/history': typeof TicketHistoryRoute
  '/blog': typeof BlogIndexRoute
  '/coupon': typeof CouponIndexRoute
  '/guide': typeof GuideIndexRoute
  '/installment': typeof InstallmentIndexRoute
  '/notification': typeof NotificationIndexRoute
  '/ticket': typeof TicketIndexRoute
  '/installment/pay/$id': typeof InstallmentPayIdRoute
  '/invoice/detail/$invoiceId': typeof InvoiceDetailInvoiceIdRoute
  '/receipt/detail/$receiptId': typeof ReceiptDetailReceiptIdRoute
  '/installment/pay': typeof InstallmentPayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/credit-check': typeof CreditCheckRoute
  '/profile': typeof ProfileRoute
  '/promotion': typeof PromotionRoute
  '/refinance-check': typeof RefinanceCheckRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/blog/$id': typeof BlogIdRoute
  '/contract/$contractId': typeof ContractContractIdRoute
  '/contract/$id': typeof ContractIdRoute
  '/coupon/$id': typeof CouponIdRoute
  '/coupon/qrcode': typeof CouponQrcodeRoute
  '/coupon/scan': typeof CouponScanRoute
  '/coupon/staff-scan': typeof CouponStaffScanRoute
  '/guide/$id': typeof GuideIdRoute
  '/invoice/$contractId': typeof InvoiceContractIdRoute
  '/notification/$id': typeof NotificationIdRoute
  '/receipt/$contractId': typeof ReceiptContractIdRoute
  '/ticket/history': typeof TicketHistoryRoute
  '/blog/': typeof BlogIndexRoute
  '/coupon/': typeof CouponIndexRoute
  '/guide/': typeof GuideIndexRoute
  '/installment/': typeof InstallmentIndexRoute
  '/notification/': typeof NotificationIndexRoute
  '/ticket/': typeof TicketIndexRoute
  '/installment/pay/$id': typeof InstallmentPayIdRoute
  '/invoice/detail/$invoiceId': typeof InvoiceDetailInvoiceIdRoute
  '/receipt/detail/$receiptId': typeof ReceiptDetailReceiptIdRoute
  '/installment/pay/': typeof InstallmentPayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/credit-check'
    | '/profile'
    | '/promotion'
    | '/refinance-check'
    | '/settings'
    | '/sign-in'
    | '/blog/$id'
    | '/contract/$contractId'
    | '/contract/$id'
    | '/coupon/$id'
    | '/coupon/qrcode'
    | '/coupon/scan'
    | '/coupon/staff-scan'
    | '/guide/$id'
    | '/invoice/$contractId'
    | '/notification/$id'
    | '/receipt/$contractId'
    | '/ticket/history'
    | '/blog'
    | '/coupon'
    | '/guide'
    | '/installment'
    | '/notification'
    | '/ticket'
    | '/installment/pay/$id'
    | '/invoice/detail/$invoiceId'
    | '/receipt/detail/$receiptId'
    | '/installment/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/credit-check'
    | '/profile'
    | '/promotion'
    | '/refinance-check'
    | '/settings'
    | '/sign-in'
    | '/blog/$id'
    | '/contract/$contractId'
    | '/contract/$id'
    | '/coupon/$id'
    | '/coupon/qrcode'
    | '/coupon/scan'
    | '/coupon/staff-scan'
    | '/guide/$id'
    | '/invoice/$contractId'
    | '/notification/$id'
    | '/receipt/$contractId'
    | '/ticket/history'
    | '/blog'
    | '/coupon'
    | '/guide'
    | '/installment'
    | '/notification'
    | '/ticket'
    | '/installment/pay/$id'
    | '/invoice/detail/$invoiceId'
    | '/receipt/detail/$receiptId'
    | '/installment/pay'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/credit-check'
    | '/profile'
    | '/promotion'
    | '/refinance-check'
    | '/settings'
    | '/sign-in'
    | '/blog/$id'
    | '/contract/$contractId'
    | '/contract/$id'
    | '/coupon/$id'
    | '/coupon/qrcode'
    | '/coupon/scan'
    | '/coupon/staff-scan'
    | '/guide/$id'
    | '/invoice/$contractId'
    | '/notification/$id'
    | '/receipt/$contractId'
    | '/ticket/history'
    | '/blog/'
    | '/coupon/'
    | '/guide/'
    | '/installment/'
    | '/notification/'
    | '/ticket/'
    | '/installment/pay/$id'
    | '/invoice/detail/$invoiceId'
    | '/receipt/detail/$receiptId'
    | '/installment/pay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CreditCheckRoute: typeof CreditCheckRoute
  ProfileRoute: typeof ProfileRoute
  PromotionRoute: typeof PromotionRoute
  RefinanceCheckRoute: typeof RefinanceCheckRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  BlogIdRoute: typeof BlogIdRoute
  ContractContractIdRoute: typeof ContractContractIdRoute
  ContractIdRoute: typeof ContractIdRoute
  CouponIdRoute: typeof CouponIdRoute
  CouponQrcodeRoute: typeof CouponQrcodeRoute
  CouponScanRoute: typeof CouponScanRoute
  CouponStaffScanRoute: typeof CouponStaffScanRoute
  GuideIdRoute: typeof GuideIdRoute
  InvoiceContractIdRoute: typeof InvoiceContractIdRoute
  NotificationIdRoute: typeof NotificationIdRoute
  ReceiptContractIdRoute: typeof ReceiptContractIdRoute
  TicketHistoryRoute: typeof TicketHistoryRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CouponIndexRoute: typeof CouponIndexRoute
  GuideIndexRoute: typeof GuideIndexRoute
  InstallmentIndexRoute: typeof InstallmentIndexRoute
  NotificationIndexRoute: typeof NotificationIndexRoute
  TicketIndexRoute: typeof TicketIndexRoute
  InstallmentPayIdRoute: typeof InstallmentPayIdRoute
  InvoiceDetailInvoiceIdRoute: typeof InvoiceDetailInvoiceIdRoute
  ReceiptDetailReceiptIdRoute: typeof ReceiptDetailReceiptIdRoute
  InstallmentPayIndexRoute: typeof InstallmentPayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refinance-check': {
      id: '/refinance-check'
      path: '/refinance-check'
      fullPath: '/refinance-check'
      preLoaderRoute: typeof RefinanceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotion': {
      id: '/promotion'
      path: '/promotion'
      fullPath: '/promotion'
      preLoaderRoute: typeof PromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-check': {
      id: '/credit-check'
      path: '/credit-check'
      fullPath: '/credit-check'
      preLoaderRoute: typeof CreditCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/': {
      id: '/ticket/'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification/': {
      id: '/notification/'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof NotificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installment/': {
      id: '/installment/'
      path: '/installment'
      fullPath: '/installment'
      preLoaderRoute: typeof InstallmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/': {
      id: '/guide/'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/': {
      id: '/coupon/'
      path: '/coupon'
      fullPath: '/coupon'
      preLoaderRoute: typeof CouponIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/history': {
      id: '/ticket/history'
      path: '/ticket/history'
      fullPath: '/ticket/history'
      preLoaderRoute: typeof TicketHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$contractId': {
      id: '/receipt/$contractId'
      path: '/receipt/$contractId'
      fullPath: '/receipt/$contractId'
      preLoaderRoute: typeof ReceiptContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification/$id': {
      id: '/notification/$id'
      path: '/notification/$id'
      fullPath: '/notification/$id'
      preLoaderRoute: typeof NotificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$contractId': {
      id: '/invoice/$contractId'
      path: '/invoice/$contractId'
      fullPath: '/invoice/$contractId'
      preLoaderRoute: typeof InvoiceContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$id': {
      id: '/guide/$id'
      path: '/guide/$id'
      fullPath: '/guide/$id'
      preLoaderRoute: typeof GuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/staff-scan': {
      id: '/coupon/staff-scan'
      path: '/coupon/staff-scan'
      fullPath: '/coupon/staff-scan'
      preLoaderRoute: typeof CouponStaffScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/scan': {
      id: '/coupon/scan'
      path: '/coupon/scan'
      fullPath: '/coupon/scan'
      preLoaderRoute: typeof CouponScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/qrcode': {
      id: '/coupon/qrcode'
      path: '/coupon/qrcode'
      fullPath: '/coupon/qrcode'
      preLoaderRoute: typeof CouponQrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/$id': {
      id: '/coupon/$id'
      path: '/coupon/$id'
      fullPath: '/coupon/$id'
      preLoaderRoute: typeof CouponIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/$id': {
      id: '/contract/$id'
      path: '/contract/$id'
      fullPath: '/contract/$id'
      preLoaderRoute: typeof ContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/$contractId': {
      id: '/contract/$contractId'
      path: '/contract/$contractId'
      fullPath: '/contract/$contractId'
      preLoaderRoute: typeof ContractContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installment/pay/': {
      id: '/installment/pay/'
      path: '/installment/pay'
      fullPath: '/installment/pay'
      preLoaderRoute: typeof InstallmentPayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/detail/$receiptId': {
      id: '/receipt/detail/$receiptId'
      path: '/receipt/detail/$receiptId'
      fullPath: '/receipt/detail/$receiptId'
      preLoaderRoute: typeof ReceiptDetailReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/detail/$invoiceId': {
      id: '/invoice/detail/$invoiceId'
      path: '/invoice/detail/$invoiceId'
      fullPath: '/invoice/detail/$invoiceId'
      preLoaderRoute: typeof InvoiceDetailInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installment/pay/$id': {
      id: '/installment/pay/$id'
      path: '/installment/pay/$id'
      fullPath: '/installment/pay/$id'
      preLoaderRoute: typeof InstallmentPayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CreditCheckRoute: CreditCheckRoute,
  ProfileRoute: ProfileRoute,
  PromotionRoute: PromotionRoute,
  RefinanceCheckRoute: RefinanceCheckRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  BlogIdRoute: BlogIdRoute,
  ContractContractIdRoute: ContractContractIdRoute,
  ContractIdRoute: ContractIdRoute,
  CouponIdRoute: CouponIdRoute,
  CouponQrcodeRoute: CouponQrcodeRoute,
  CouponScanRoute: CouponScanRoute,
  CouponStaffScanRoute: CouponStaffScanRoute,
  GuideIdRoute: GuideIdRoute,
  InvoiceContractIdRoute: InvoiceContractIdRoute,
  NotificationIdRoute: NotificationIdRoute,
  ReceiptContractIdRoute: ReceiptContractIdRoute,
  TicketHistoryRoute: TicketHistoryRoute,
  BlogIndexRoute: BlogIndexRoute,
  CouponIndexRoute: CouponIndexRoute,
  GuideIndexRoute: GuideIndexRoute,
  InstallmentIndexRoute: InstallmentIndexRoute,
  NotificationIndexRoute: NotificationIndexRoute,
  TicketIndexRoute: TicketIndexRoute,
  InstallmentPayIdRoute: InstallmentPayIdRoute,
  InvoiceDetailInvoiceIdRoute: InvoiceDetailInvoiceIdRoute,
  ReceiptDetailReceiptIdRoute: ReceiptDetailReceiptIdRoute,
  InstallmentPayIndexRoute: InstallmentPayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
