/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PromotionRouteImport } from './routes/promotion'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketIndexRouteImport } from './routes/ticket/index'
import { Route as NotificationIndexRouteImport } from './routes/notification/index'
import { Route as InstallmentIndexRouteImport } from './routes/installment/index'
import { Route as GuideIndexRouteImport } from './routes/guide/index'
import { Route as CouponIndexRouteImport } from './routes/coupon/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TicketHistoryRouteImport } from './routes/ticket/history'
import { Route as ReceiptIdRouteImport } from './routes/receipt/$id'
import { Route as ReceiptContractIdRouteImport } from './routes/receipt/$contractId'
import { Route as NotificationIdRouteImport } from './routes/notification/$id'
import { Route as InvoiceIdRouteImport } from './routes/invoice/$id'
import { Route as InvoiceContractIdRouteImport } from './routes/invoice/$contractId'
import { Route as GuideIdRouteImport } from './routes/guide/$id'
import { Route as CouponStaffScanRouteImport } from './routes/coupon/staff-scan'
import { Route as CouponScanRouteImport } from './routes/coupon/scan'
import { Route as CouponQrcodeRouteImport } from './routes/coupon/qrcode'
import { Route as CouponIdRouteImport } from './routes/coupon/$id'
import { Route as ContractIdRouteImport } from './routes/contract/$id'
import { Route as ContractContractIdRouteImport } from './routes/contract/$contractId'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as InstallmentPayIndexRouteImport } from './routes/installment/pay/index'
import { Route as ReceiptContractIdReceiptIdRouteImport } from './routes/receipt/$contractId/$receiptId'
import { Route as InvoiceContractIdInvoiceIdRouteImport } from './routes/invoice/$contractId/$invoiceId'
import { Route as InstallmentPayIdRouteImport } from './routes/installment/pay/$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionRoute = PromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIndexRoute = TicketIndexRouteImport.update({
  id: '/ticket/',
  path: '/ticket/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationIndexRoute = NotificationIndexRouteImport.update({
  id: '/notification/',
  path: '/notification/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentIndexRoute = InstallmentIndexRouteImport.update({
  id: '/installment/',
  path: '/installment/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponIndexRoute = CouponIndexRouteImport.update({
  id: '/coupon/',
  path: '/coupon/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketHistoryRoute = TicketHistoryRouteImport.update({
  id: '/ticket/history',
  path: '/ticket/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptContractIdRoute = ReceiptContractIdRouteImport.update({
  id: '/receipt/$contractId',
  path: '/receipt/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationIdRoute = NotificationIdRouteImport.update({
  id: '/notification/$id',
  path: '/notification/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceContractIdRoute = InvoiceContractIdRouteImport.update({
  id: '/invoice/$contractId',
  path: '/invoice/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIdRoute = GuideIdRouteImport.update({
  id: '/guide/$id',
  path: '/guide/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponStaffScanRoute = CouponStaffScanRouteImport.update({
  id: '/coupon/staff-scan',
  path: '/coupon/staff-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponScanRoute = CouponScanRouteImport.update({
  id: '/coupon/scan',
  path: '/coupon/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponQrcodeRoute = CouponQrcodeRouteImport.update({
  id: '/coupon/qrcode',
  path: '/coupon/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponIdRoute = CouponIdRouteImport.update({
  id: '/coupon/$id',
  path: '/coupon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractIdRoute = ContractIdRouteImport.update({
  id: '/contract/$id',
  path: '/contract/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractContractIdRoute = ContractContractIdRouteImport.update({
  id: '/contract/$contractId',
  path: '/contract/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentPayIndexRoute = InstallmentPayIndexRouteImport.update({
  id: '/installment/pay/',
  path: '/installment/pay/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptContractIdReceiptIdRoute =
  ReceiptContractIdReceiptIdRouteImport.update({
    id: '/$receiptId',
    path: '/$receiptId',
    getParentRoute: () => ReceiptContractIdRoute,
  } as any)
const InvoiceContractIdInvoiceIdRoute =
  InvoiceContractIdInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => InvoiceContractIdRoute,
  } as any)
const InstallmentPayIdRoute = InstallmentPayIdRouteImport.update({
  id: '/installment/pay/$id',
  path: '/installment/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/promotion': typeof PromotionRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/blog/$id': typeof BlogIdRoute
  '/contract/$contractId': typeof ContractContractIdRoute
  '/contract/$id': typeof ContractIdRoute
  '/coupon/$id': typeof CouponIdRoute
  '/coupon/qrcode': typeof CouponQrcodeRoute
  '/coupon/scan': typeof CouponScanRoute
  '/coupon/staff-scan': typeof CouponStaffScanRoute
  '/guide/$id': typeof GuideIdRoute
  '/invoice/$contractId': typeof InvoiceContractIdRouteWithChildren
  '/invoice/$id': typeof InvoiceIdRoute
  '/notification/$id': typeof NotificationIdRoute
  '/receipt/$contractId': typeof ReceiptContractIdRouteWithChildren
  '/receipt/$id': typeof ReceiptIdRoute
  '/ticket/history': typeof TicketHistoryRoute
  '/blog': typeof BlogIndexRoute
  '/coupon': typeof CouponIndexRoute
  '/guide': typeof GuideIndexRoute
  '/installment': typeof InstallmentIndexRoute
  '/notification': typeof NotificationIndexRoute
  '/ticket': typeof TicketIndexRoute
  '/installment/pay/$id': typeof InstallmentPayIdRoute
  '/invoice/$contractId/$invoiceId': typeof InvoiceContractIdInvoiceIdRoute
  '/receipt/$contractId/$receiptId': typeof ReceiptContractIdReceiptIdRoute
  '/installment/pay': typeof InstallmentPayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/promotion': typeof PromotionRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/blog/$id': typeof BlogIdRoute
  '/contract/$contractId': typeof ContractContractIdRoute
  '/contract/$id': typeof ContractIdRoute
  '/coupon/$id': typeof CouponIdRoute
  '/coupon/qrcode': typeof CouponQrcodeRoute
  '/coupon/scan': typeof CouponScanRoute
  '/coupon/staff-scan': typeof CouponStaffScanRoute
  '/guide/$id': typeof GuideIdRoute
  '/invoice/$contractId': typeof InvoiceContractIdRouteWithChildren
  '/invoice/$id': typeof InvoiceIdRoute
  '/notification/$id': typeof NotificationIdRoute
  '/receipt/$contractId': typeof ReceiptContractIdRouteWithChildren
  '/receipt/$id': typeof ReceiptIdRoute
  '/ticket/history': typeof TicketHistoryRoute
  '/blog': typeof BlogIndexRoute
  '/coupon': typeof CouponIndexRoute
  '/guide': typeof GuideIndexRoute
  '/installment': typeof InstallmentIndexRoute
  '/notification': typeof NotificationIndexRoute
  '/ticket': typeof TicketIndexRoute
  '/installment/pay/$id': typeof InstallmentPayIdRoute
  '/invoice/$contractId/$invoiceId': typeof InvoiceContractIdInvoiceIdRoute
  '/receipt/$contractId/$receiptId': typeof ReceiptContractIdReceiptIdRoute
  '/installment/pay': typeof InstallmentPayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/promotion': typeof PromotionRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/blog/$id': typeof BlogIdRoute
  '/contract/$contractId': typeof ContractContractIdRoute
  '/contract/$id': typeof ContractIdRoute
  '/coupon/$id': typeof CouponIdRoute
  '/coupon/qrcode': typeof CouponQrcodeRoute
  '/coupon/scan': typeof CouponScanRoute
  '/coupon/staff-scan': typeof CouponStaffScanRoute
  '/guide/$id': typeof GuideIdRoute
  '/invoice/$contractId': typeof InvoiceContractIdRouteWithChildren
  '/invoice/$id': typeof InvoiceIdRoute
  '/notification/$id': typeof NotificationIdRoute
  '/receipt/$contractId': typeof ReceiptContractIdRouteWithChildren
  '/receipt/$id': typeof ReceiptIdRoute
  '/ticket/history': typeof TicketHistoryRoute
  '/blog/': typeof BlogIndexRoute
  '/coupon/': typeof CouponIndexRoute
  '/guide/': typeof GuideIndexRoute
  '/installment/': typeof InstallmentIndexRoute
  '/notification/': typeof NotificationIndexRoute
  '/ticket/': typeof TicketIndexRoute
  '/installment/pay/$id': typeof InstallmentPayIdRoute
  '/invoice/$contractId/$invoiceId': typeof InvoiceContractIdInvoiceIdRoute
  '/receipt/$contractId/$receiptId': typeof ReceiptContractIdReceiptIdRoute
  '/installment/pay/': typeof InstallmentPayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/profile'
    | '/promotion'
    | '/settings'
    | '/sign-in'
    | '/blog/$id'
    | '/contract/$contractId'
    | '/contract/$id'
    | '/coupon/$id'
    | '/coupon/qrcode'
    | '/coupon/scan'
    | '/coupon/staff-scan'
    | '/guide/$id'
    | '/invoice/$contractId'
    | '/invoice/$id'
    | '/notification/$id'
    | '/receipt/$contractId'
    | '/receipt/$id'
    | '/ticket/history'
    | '/blog'
    | '/coupon'
    | '/guide'
    | '/installment'
    | '/notification'
    | '/ticket'
    | '/installment/pay/$id'
    | '/invoice/$contractId/$invoiceId'
    | '/receipt/$contractId/$receiptId'
    | '/installment/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/profile'
    | '/promotion'
    | '/settings'
    | '/sign-in'
    | '/blog/$id'
    | '/contract/$contractId'
    | '/contract/$id'
    | '/coupon/$id'
    | '/coupon/qrcode'
    | '/coupon/scan'
    | '/coupon/staff-scan'
    | '/guide/$id'
    | '/invoice/$contractId'
    | '/invoice/$id'
    | '/notification/$id'
    | '/receipt/$contractId'
    | '/receipt/$id'
    | '/ticket/history'
    | '/blog'
    | '/coupon'
    | '/guide'
    | '/installment'
    | '/notification'
    | '/ticket'
    | '/installment/pay/$id'
    | '/invoice/$contractId/$invoiceId'
    | '/receipt/$contractId/$receiptId'
    | '/installment/pay'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/profile'
    | '/promotion'
    | '/settings'
    | '/sign-in'
    | '/blog/$id'
    | '/contract/$contractId'
    | '/contract/$id'
    | '/coupon/$id'
    | '/coupon/qrcode'
    | '/coupon/scan'
    | '/coupon/staff-scan'
    | '/guide/$id'
    | '/invoice/$contractId'
    | '/invoice/$id'
    | '/notification/$id'
    | '/receipt/$contractId'
    | '/receipt/$id'
    | '/ticket/history'
    | '/blog/'
    | '/coupon/'
    | '/guide/'
    | '/installment/'
    | '/notification/'
    | '/ticket/'
    | '/installment/pay/$id'
    | '/invoice/$contractId/$invoiceId'
    | '/receipt/$contractId/$receiptId'
    | '/installment/pay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ProfileRoute: typeof ProfileRoute
  PromotionRoute: typeof PromotionRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  BlogIdRoute: typeof BlogIdRoute
  ContractContractIdRoute: typeof ContractContractIdRoute
  ContractIdRoute: typeof ContractIdRoute
  CouponIdRoute: typeof CouponIdRoute
  CouponQrcodeRoute: typeof CouponQrcodeRoute
  CouponScanRoute: typeof CouponScanRoute
  CouponStaffScanRoute: typeof CouponStaffScanRoute
  GuideIdRoute: typeof GuideIdRoute
  InvoiceContractIdRoute: typeof InvoiceContractIdRouteWithChildren
  InvoiceIdRoute: typeof InvoiceIdRoute
  NotificationIdRoute: typeof NotificationIdRoute
  ReceiptContractIdRoute: typeof ReceiptContractIdRouteWithChildren
  ReceiptIdRoute: typeof ReceiptIdRoute
  TicketHistoryRoute: typeof TicketHistoryRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CouponIndexRoute: typeof CouponIndexRoute
  GuideIndexRoute: typeof GuideIndexRoute
  InstallmentIndexRoute: typeof InstallmentIndexRoute
  NotificationIndexRoute: typeof NotificationIndexRoute
  TicketIndexRoute: typeof TicketIndexRoute
  InstallmentPayIdRoute: typeof InstallmentPayIdRoute
  InstallmentPayIndexRoute: typeof InstallmentPayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotion': {
      id: '/promotion'
      path: '/promotion'
      fullPath: '/promotion'
      preLoaderRoute: typeof PromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/': {
      id: '/ticket/'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification/': {
      id: '/notification/'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof NotificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installment/': {
      id: '/installment/'
      path: '/installment'
      fullPath: '/installment'
      preLoaderRoute: typeof InstallmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/': {
      id: '/guide/'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/': {
      id: '/coupon/'
      path: '/coupon'
      fullPath: '/coupon'
      preLoaderRoute: typeof CouponIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/history': {
      id: '/ticket/history'
      path: '/ticket/history'
      fullPath: '/ticket/history'
      preLoaderRoute: typeof TicketHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$contractId': {
      id: '/receipt/$contractId'
      path: '/receipt/$contractId'
      fullPath: '/receipt/$contractId'
      preLoaderRoute: typeof ReceiptContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification/$id': {
      id: '/notification/$id'
      path: '/notification/$id'
      fullPath: '/notification/$id'
      preLoaderRoute: typeof NotificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$contractId': {
      id: '/invoice/$contractId'
      path: '/invoice/$contractId'
      fullPath: '/invoice/$contractId'
      preLoaderRoute: typeof InvoiceContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$id': {
      id: '/guide/$id'
      path: '/guide/$id'
      fullPath: '/guide/$id'
      preLoaderRoute: typeof GuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/staff-scan': {
      id: '/coupon/staff-scan'
      path: '/coupon/staff-scan'
      fullPath: '/coupon/staff-scan'
      preLoaderRoute: typeof CouponStaffScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/scan': {
      id: '/coupon/scan'
      path: '/coupon/scan'
      fullPath: '/coupon/scan'
      preLoaderRoute: typeof CouponScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/qrcode': {
      id: '/coupon/qrcode'
      path: '/coupon/qrcode'
      fullPath: '/coupon/qrcode'
      preLoaderRoute: typeof CouponQrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/$id': {
      id: '/coupon/$id'
      path: '/coupon/$id'
      fullPath: '/coupon/$id'
      preLoaderRoute: typeof CouponIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/$id': {
      id: '/contract/$id'
      path: '/contract/$id'
      fullPath: '/contract/$id'
      preLoaderRoute: typeof ContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/$contractId': {
      id: '/contract/$contractId'
      path: '/contract/$contractId'
      fullPath: '/contract/$contractId'
      preLoaderRoute: typeof ContractContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installment/pay/': {
      id: '/installment/pay/'
      path: '/installment/pay'
      fullPath: '/installment/pay'
      preLoaderRoute: typeof InstallmentPayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$contractId/$receiptId': {
      id: '/receipt/$contractId/$receiptId'
      path: '/$receiptId'
      fullPath: '/receipt/$contractId/$receiptId'
      preLoaderRoute: typeof ReceiptContractIdReceiptIdRouteImport
      parentRoute: typeof ReceiptContractIdRoute
    }
    '/invoice/$contractId/$invoiceId': {
      id: '/invoice/$contractId/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoice/$contractId/$invoiceId'
      preLoaderRoute: typeof InvoiceContractIdInvoiceIdRouteImport
      parentRoute: typeof InvoiceContractIdRoute
    }
    '/installment/pay/$id': {
      id: '/installment/pay/$id'
      path: '/installment/pay/$id'
      fullPath: '/installment/pay/$id'
      preLoaderRoute: typeof InstallmentPayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InvoiceContractIdRouteChildren {
  InvoiceContractIdInvoiceIdRoute: typeof InvoiceContractIdInvoiceIdRoute
}

const InvoiceContractIdRouteChildren: InvoiceContractIdRouteChildren = {
  InvoiceContractIdInvoiceIdRoute: InvoiceContractIdInvoiceIdRoute,
}

const InvoiceContractIdRouteWithChildren =
  InvoiceContractIdRoute._addFileChildren(InvoiceContractIdRouteChildren)

interface ReceiptContractIdRouteChildren {
  ReceiptContractIdReceiptIdRoute: typeof ReceiptContractIdReceiptIdRoute
}

const ReceiptContractIdRouteChildren: ReceiptContractIdRouteChildren = {
  ReceiptContractIdReceiptIdRoute: ReceiptContractIdReceiptIdRoute,
}

const ReceiptContractIdRouteWithChildren =
  ReceiptContractIdRoute._addFileChildren(ReceiptContractIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ProfileRoute: ProfileRoute,
  PromotionRoute: PromotionRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  BlogIdRoute: BlogIdRoute,
  ContractContractIdRoute: ContractContractIdRoute,
  ContractIdRoute: ContractIdRoute,
  CouponIdRoute: CouponIdRoute,
  CouponQrcodeRoute: CouponQrcodeRoute,
  CouponScanRoute: CouponScanRoute,
  CouponStaffScanRoute: CouponStaffScanRoute,
  GuideIdRoute: GuideIdRoute,
  InvoiceContractIdRoute: InvoiceContractIdRouteWithChildren,
  InvoiceIdRoute: InvoiceIdRoute,
  NotificationIdRoute: NotificationIdRoute,
  ReceiptContractIdRoute: ReceiptContractIdRouteWithChildren,
  ReceiptIdRoute: ReceiptIdRoute,
  TicketHistoryRoute: TicketHistoryRoute,
  BlogIndexRoute: BlogIndexRoute,
  CouponIndexRoute: CouponIndexRoute,
  GuideIndexRoute: GuideIndexRoute,
  InstallmentIndexRoute: InstallmentIndexRoute,
  NotificationIndexRoute: NotificationIndexRoute,
  TicketIndexRoute: TicketIndexRoute,
  InstallmentPayIdRoute: InstallmentPayIdRoute,
  InstallmentPayIndexRoute: InstallmentPayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
